### ISSUE TITLE
Orderstruktur anlegen unter "Code"

### ISSUE THREAD

**Issue by DrHannaHuebner** [Fuenfgeld/DMA2024TeamB#12]
Die Dateien, die unter Code abgelegt wurden werden unübersichtlich. Vielleicht könnte jemand eine Ordnerstruktur anlegen. Weiß jemand wie das geht?

**Comment by Jotina** [comment]
ja kein Problem. Mit UNIX commands kann man das im GitBash machen.
Ich mache mal eine Vorschlag.

**Comment by Jotina** [comment]
Daten Verschieben im Repository (FYI) mit GitBash

cd -> go to GitHub repository auf deinem Computer
mkdir -> erstelle eine Ordner z.B: mkdir Daten
mv -> move files to Daten/ z.B.: mv file1 file2 file3 Daten/ 
git add . -> Fügt die Äderungen zu Statingbereich
git commit -m "was man gemacht hat" -> Kommentier was man gemacht hat
git push origin main -> pushed Änderung zu GitHub
