### ISSUE TITLE
Präsentation (PowerPoint + Skript)

### ISSUE THREAD

**Issue by doadhe** [Fuenfgeld/DMA2024TeamB#17]

**Comment by DrHannaHuebner** [comment]
Das Skript ist nur für unsere grobe Planung. Das kann direkt als Google Slide angelegt werden und wir bekommen anhand dessen Feedback. Die Präsentation soll so gestaltet werden, dass es jemand versteht, der keine Ahnung von allem hat (Mama/Papa). Wir sollen uns auf ein Alleinstellungsmerkmal fokussieren und dies hervorheben (im Vergleich zu den anderen Gruppen)..
Dauer 15-20min.
