### ISSUE TITLE
Datenschutzfolgeabschätzung

### ISSUE THREAD

**Issue by doadhe** [Fuenfgeld/DMA2024TeamB#18]

**Comment by DrHannaHuebner** [comment]
Vorlage liegt in KW 5 ab und soll genutzt werden und so ins WIKI eingebunden werden. Die DSFA soll dann auch im Data Management Plan verlinkt werden. Ziel ist es Risiken zu identifizieren und Maßnahmen zum Mittigeren darlegen. Bsp.: Statt Klarnamen die PatId und Name separat aufbewahren.

**Comment by Jotina** [comment]
- [x] Link zu Pseudoanonymierung fehlt noch
https://github.com/Fuenfgeld/DMA2024TeamB/wiki/Datenschutzfolgeabsch%C3%A4tzung#anonymisierung--pseudonymisierung

**Comment by DrHannaHuebner** [comment]
Alles erledigt. Kann geschlossen werden.
