### ISSUE TITLE
Archivierungskonzept

### ISSUE THREAD

**Issue by doadhe** [Fuenfgeld/DMA2024TeamB#19]

**Comment by DrHannaHuebner** [comment]
Zu beantworten: Was ist die Lizenz / Was soll archiviert werden / Was sind Artefakte

Wir sollen uns an den Projekten der Vorgänger orientieren (z.B. Gruppe A von 2023)

**Comment by Jotina** [comment]
Habe mal eine Seite im WIKI entworfen "Archivierungskonsept"
https://github.com/Fuenfgeld/DMA2024TeamB/wiki/Archivierungskonzept
