### ISSUE TITLE
Colab Books reproduzierbar machen (?)

### ISSUE THREAD

**Issue by doadhe** [Fuenfgeld/DMA2024TeamB#20]

**Comment by DrHannaHuebner** [comment]
Ich habe das für das ETL Colab Book schon mal erledigt: [https://github.com/Fuenfgeld/DMA2024TeamB/blob/main/Code/Datawarehouse_TeamB_V2_20240204.ipynb](url) Geb gerne Rückmeldung, ob euch das so taugt.

**Comment by DrHannaHuebner** [comment]
@Jotina , kannst du die zwei Alten DataWarehouse Codes vlt aus den Code Dateien rauslöschen? Sonst weiß man als Externer nicht, welches der korrekte Code ist: 
![image](https://github.com/Fuenfgeld/DMA2024TeamB/assets/156616648/6b1a6dbf-ce6d-4192-b490-8c3b051c555d)
