### ISSUE TITLE
Wiki aktualisieren/Layout optimieren

### ISSUE THREAD

**Issue by doadhe** [Fuenfgeld/DMA2024TeamB#21]

**Comment by Jotina** [comment]
Inhaltsverzeichniss mal vorgefertigt: 
https://github.com/Fuenfgeld/DMA2024TeamB/wiki

**Comment by Jotina** [comment]
WIr haben jetzt auch was auf "HOME" stehen -> ein Bild wäre cool. Ist wer graphisch begabt?

**Comment by DrHannaHuebner** [comment]
@Strubbelig magst du deine Grafik aus der Präsentation vlt. noch auf die ReadMe und HOME Seite einfügen?
