### ISSUE TITLE
Jupyter Notebook nicht ausführbar

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamB#27]
![image](https://github.com/Fuenfgeld/DMA2024TeamB/assets/32547123/1d5d6e5d-1712-4184-a5ab-b0c0e22edb57)

**Comment by Fuenfgeld** [comment]
Wie wollt ihr Zugang zu euren Daten geben?

Share drive, GitHub etc, Eure Notebook sollte ausführbar sein. Im moment habe ich keine möglichkeit auf euren Datensatz zuzugreifen

**Comment by doadhe** [comment]
Sollte jetzt funktionieren - bitte nochmals versuchen
