### ISSUE TITLE
Eure Code basis muss aufgeräumt werden. Es ist nicht klar der finale Code ist.

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamB#28]
![image](https://github.com/Fuenfgeld/DMA2024TeamB/assets/32547123/b3f6da77-436c-4c9e-9f92-d17415afbfd1)

**Comment by doadhe** [comment]
Finaler Code für die Exploratory Data Analysis:
https://github.com/Fuenfgeld/DMA2024TeamB/blob/b76c5b80116c256bee6e833039f69c1eca1dbed5/Code/final_EDA_TeamB_Precise_BC.ipynb
