### ISSUE TITLE
Forschungsfrage

### ISSUE THREAD

**Issue by Jotina** [Fuenfgeld/DMA2024TeamB#3]
Exploration DB und Forschungsfrage erstellen

**Comment by DrHannaHuebner** [comment]
Nur 11 Patienten mit Brustkrebs liegen vor.

**Comment by Jotina** [comment]
ok wie Besprochen wir beschränken uns auf diese 11

**Comment by DrHannaHuebner** [comment]
Studienziele wurden unter https://github.com/Fuenfgeld/DMA2024TeamB.wiki.git ausformuliert
