### ISSUE TITLE
ETL Prozess

### ISSUE THREAD

**Issue by DrHannaHuebner** [Fuenfgeld/DMA2024TeamB#7]
ETL Prozess in Python ausarbeiten

**Comment by Strubbelig** [comment]
[Stern-Schema](https://github.com/Fuenfgeld/DMA2024TeamB/wiki/ETL%E2%80%90Prozess#star-schema-des-data-warehouses)

Erstellen der einzelnen Tabellen als SQL Abfrage allein oder SQL in Python: 
- [x] d_Agegroups
- [x] d_Comorbidity
- [x] d_Cancertherapy
- [x] d_Medication
- [x]  d_Primarytumor
- [x]  d_Patients
- [x]  F_BreastCancerQoL

**Comment by DrHannaHuebner** [comment]
Ich habe eine SQL Datenbank mit den Tabellen erstellt: SQL_TeamB_Warehouse_V2_20240203.db
Der Code zum Durchlaufen liegt hier: SQL_Warehouse
 
 **d_primaryTumor fehlt noch**

**Comment by DrHannaHuebner** [comment]
Ich habe den Task in ein Colab Book eingearbeitet. Bei mir funktionierts. Bitte alle mal testen: Datawarehouse_TeamB_V1_20240204.ipynb
Bei anderen Teams kann man im GitHub Code direkt klicken "Open in Colab". Das habe ich leider noch nicht rausbekommen, wie das funktioniert.

**Comment by Strubbelig** [comment]
Brauchen wir jetzt noch d_primaryTumor? Ist aus dem Sternschema raus...

**Comment by DrHannaHuebner** [comment]
Sorry, d_primarytumor ist bei mir untergegangen. Ich hatte das bei der Fact-Tabelle vergessen und dann ist es auch aus dem aktualisierten Sterndiagram rausgeflogen. Ich habe es wieder ergänzt. Kann es auch später noch zum Warehouse-Code hinzufügen.

**Comment by DrHannaHuebner** [comment]
Es gibt ein neues Update von der SQL Datenbank [https://github.com/Fuenfgeld/DMA2024TeamB/blob/main/SQL_Warehouse_V2_20240204](url) und dem zugehörigem Colab Skript zur Erstellung dieser:  [https://github.com/Fuenfgeld/DMA2024TeamB/blob/main/Datawarehouse_TeamB_V2_20240204.ipynb](url) @Jotina , leider hat das Plazieren beider Dokumente in den entsprechenden Ordnern wieder nicht geklappt. Entsprechend müssten die nochmal verschoben werden ... sorry.

**Comment by DrHannaHuebner** [comment]
Ich habe die Beschreibung des CODES umfangreich ergänzt: [https://github.com/Fuenfgeld/DMA2024TeamB/blob/main/Code/Datawarehouse_TeamB_V2_20240204.ipynb](url)
und das Wiki: [https://github.com/Fuenfgeld/DMA2024TeamB/wiki/ETL%E2%80%90Prozess](url) an der entsprechenden Stelle finalisiert
