### ISSUE TITLE
Star Schema

### ISSUE THREAD

**Issue by DrHannaHuebner** [Fuenfgeld/DMA2024TeamB#9]
WIe bekomme ich in einem Star Schema die Start- und Stop-Zeiten von medikamentöser Behandlung sinnvoll unter?
Der primäre Outcome-Parameter ist QALY Score. Hier gibt es bereits mehrere pro Patient. 
Die Medikamentöse Behandlung ist wichtig für sekundäre Studienziele. Hier ist es wichtig zu wissen, wann diese gestartet und geendet hat.
Sollte man hier mit zwei Fact-Tabellen arbeiten oder statt einem Star Schema eher ein Snow-Flake Schema wählen?

Hier erste Überlegungen zum Data Warehouse Schema: 
[]https://dbdiagram.io/d/65b6c387ac844320aee48012

![DateWarehouse_Schema_V1](https://github.com/Fuenfgeld/DMA2024TeamB/assets/156616648/ae63445a-c8fb-4ea6-a47b-3555337a01ef)

**Comment by Fuenfgeld** [comment]
Es gibt mehre Möglichkeiten. etweder ihr bildet die Differenz und speichert diese. oder folgendes:

## 1. Erweiterung der Fact-Tabelle

Eine Möglichkeit besteht darin, die Fact-Tabelle zu erweitern, um die Start- und Stop-Zeiten direkt einzuschließen. Dies könnte durch Hinzufügen von zwei zusätzlichen Spalten geschehen:

    BehandlungsStart: Datum und Zeit des Beginns der medikamentösen Behandlung.
    BehandlungsEnde: Datum und Zeit des Endes der medikamentösen Behandlung.

Diese Methode ermöglicht eine direkte Analyse der Behandlungsdauer und deren Überlappung mit anderen relevanten Ereignissen oder Zuständen des Patienten.
## 2. Verwendung von zwei Fact-Tabellen
Eine andere Lösung ist die Verwendung von zwei separaten Fact-Tabellen: eine für den QALY Score und eine andere für die medikamentöse Behandlung. Die Fact-Tabelle für die medikamentöse Behandlung würde spezifische Attribute der Behandlung enthalten, einschließlich der Start- und Stop-Zeiten. Diese Struktur ermöglicht eine flexible und detaillierte Analyse der Behandlungsdaten parallel zu den QALY Scores.

## 3. Übergang zum Snowflake-Schema
Das Snowflake-Schema, eine Erweiterung des Star Schemas, bei der die Dimensionstabellen in weitere Ebenen von Dimensionstabellen normalisiert werden, könnte ebenfalls in Betracht gezogen werden. Hier könnten Sie eine separate Dimensionstabelle für medikamentöse Behandlungen erstellen, die Details zur Behandlung, einschließlich Start- und Endzeiten, enthält. Diese Methode erhöht die Komplexität des Schemas, ermöglicht aber eine feinere Granularität und Flexibilität bei der Analyse.
